spring:
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/foresty?useSSL=false
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: true