
---
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:foresty'
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-foresty
---
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:foresty'
    username: test
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
      path: /h2-foresty
---
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:foresty'
    username: foresty-prod
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none