
---
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/foresty
    username: root
    password: 1234
#  exposed:
#    generate-ddl: false
#    show-sql: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
#    open-in-view: false
---
spring:
  profiles:
    active: dev
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/foresty
#    username: root
#    password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
---
spring:
  profiles:
    active: prod