server:
  port: 8111
  tomcat:
    threads:
      max: 200
    max-connections: 8192
    accept-count: 100
    connection-timeout: 20000
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  profiles:
    active: local
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic
  output:
    ansi:
      enabled: always
logging:
  level:
    root: info
    org.jetbrains.exposed: debug
    org.hibernate.sql: debug
    org.hibernate.type: trace
management:
  endpoints:
    web:
      exposure:
        exclude: health, info, beans, conditions
        include: threaddump, heapdump