server:
  port: 8111
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic
logging:
  level:
    root: info
#    org.hibernate.sql: debug
#    org.hibernate.type: trace
---
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/foresty
    username: root
    password: 1234
  exposed:
    generate-ddl: true
    show-sql: true
---
spring:
  profiles:
    active: dev
---
spring:
  profiles:
    active: prod