server:
  port: 8111
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic
logging:
  level:
    root: info
    org.hibernate.sql: debug
    org.hibernate.type: trace
---
spring:
  profiles:
    active: local
---
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:foresty'
    username: test
    password: 1234
---
spring:
  profiles:
    active: prod