spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/foresty
    username: root
    password: 1234
#  exposed:
#    generate-ddl: false
#    show-sql: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
